### ISSUE TITLE
Server data not displayed

### ISSUE THREAD

**Issue by maxdrs** [tolleiv/dashing-zabbix#2]
Hi, 
all working fine  but I don't see the webpart relative to server, in attachment example of screenshot .
Do you know why?
thks

![image](https://cloud.githubusercontent.com/assets/12641181/7857323/d7efa81a-052f-11e5-9877-3777dc625fa6.png)

**Comment by tolleiv** [comment]
Uhm I changed a lot of stuff since then which I didn't push yet. Do you get any error's from the dashing jobs? Does your API user have sufficient rights to read the host data?

Cheers

**Comment by maxdrs** [comment]
No error on console, I looking for more details.
thank you
Max
