### ISSUE TITLE
Multiple Zabbix Servers

### ISSUE THREAD

**Issue by dj-wasabi** [tolleiv/dashing-zabbix#3]
Hi,

I was curious if you can also configure multiple zabbix-servers into 1 dashboard? I'm looking for an solution for our support employees when they can have insights from multiple zabbix-servers on an single dashboard.

I hope to hear from you.
Kind regards,

Werner

**Comment by tolleiv** [comment]
Hi,
you'd just have to replicate the jobs/zabbix.rb for each Zabbix server and send the events with a server specific key.
Not sure how I could help atm.
Cheers
