### ISSUE TITLE
Zabby::ResponseCodeError

### ISSUE THREAD

**Issue by thomasgogo** [tolleiv/dashing-zabbix#4]
scheduler caught exception:
Zabby::ResponseCodeError
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/connection.rb:139:in `query_zabbix_rpc'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/connection.rb:63:in`rescue in authenticate'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/connection.rb:54:in `authenticate'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/connection.rb:37:in`login'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/shell_helpers.rb:71:in `login'
/opt/sweet_dashboard_project/jobs/zabbix.rb:24:in`block (2 levels) in <top (required)>'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/runner.rb:50:in `instance_eval'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby/runner.rb:50:in`run'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/zabby-0.1.2/lib/zabby.rb:25:in `init'
/opt/sweet_dashboard_project/jobs/zabbix.rb:20:in`block in <top (required)>'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`trigger_block'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`call'
/opt/sweet_dashboard_project/vendor/ruby/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

dashing start,the thin.log error!
@tolleiv

**Comment by tolleiv** [comment]
Hi, looks like the Gem is not able to authenticate. Might be due to incompatible changes in newer Zabbix versions - but that's hards to see from the stacktrace alone.
Cheers

**Comment by rastafrange** [comment]
Hello, 
I have the same issue : 
scheduler caught exception:

```
Zabby::APIError
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/connection.rb:125:in `format_exception'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/connection.rb:146:in `query_zabbix_rpc'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/connection.rb:63:in `rescue in authenticate'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/connection.rb:54:in `authenticate'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/connection.rb:37:in `login'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/shell_helpers.rb:71:in `login'
/home/appliance/zabbix_dashboard/jobs/zabbix.rb:24:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/runner.rb:50:in `instance_eval'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby/runner.rb:50:in `run'
/var/lib/gems/2.2.0/gems/zabby-0.1.2/lib/zabby.rb:25:in `init'
/home/appliance/zabbix_dashboard/jobs/zabbix.rb:20:in `block in <top (required)>'
/var/lib/gems/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/2.2.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

when i run dashing start

How can i resolve this ? @tolleiv
