### ISSUE TITLE
zabbix 3.0

### ISSUE THREAD

**Issue by dkew8** [tolleiv/dashing-zabbix#6]
Somewhere between versions 2.2 and 2.4 host field was removed from zabbix api response. It's now required to remove expandData field from api request and add selectHost field.

**Comment by 6LYTH3** [comment]
Hi @dkew8 
I think that [my pull request](https://github.com/tolleiv/dashing-zabbix/pull/7#issue-176302852) can fix this change.

**Comment by tolleiv** [comment]
Indeed this looks fine ... to be honest I'm using a different implementation nowadays but wasn't able to publish that one so far ... that's for the PR

**Comment by tolleiv** [comment]
@dkew8 I assume the PR resolved that one for you too?

**Comment by dkew8** [comment]
Yes, I've came up to something like this too. Thanks.
